### PR TITLE
Feature: Toggle usage of gift cards via settings

### PR DESCRIPTION
**Pull request by R4Nilluminatixs**
Make it possible to enable or disable the usage of gift cards throughout the shop via the settings.

Closes: feature/toggle-usage-of-giftcards

Note: this does keep the giftcard elements available for the admin, its pointed towards user interactions / notifications.

### CODE REVIEW

**Comment by R4Nilluminatixs** [comment]
Screenshot from 2024-02-24 19-30-34
^ Setting added in shop settings

Screenshot from 2024-02-24 19-31-15
^ Gift card disabled view: Cart

Screenshot from 2024-02-24 19-31-50
^ Gift card disabled view: profile

**Comment by MrMicky-FR** [comment]
What do you think of instead hiding the giftcard input if no valid giftcard exists ?

**Comment by R4Nilluminatixs** [comment]
> What do you think of instead hiding the giftcard input if no valid giftcard exists ? - @MrMicky-FR 

That might be a possibility, but that would introduce "magic" (As in: Sometimes its there, sometimes its not there. No explanation why.) to the way giftcards work. A hard button to enable or disable the usage of a giftcard would be more clear and would save us on writing additional documentation explaining how the "magic" giftcard system works.

**Comment by R4Nilluminatixs** [comment]
- [ ] Update cart/Cart.php to always disallow adding and removing giftcards if disabled
- [ ] Update cart/Cart.php to always set the result of payableTotal() to $this->total if disabled

**Pull request closed without merging**
